id: I9A58C9BF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:41:48+00:00'
last_modified: '2022-06-08T11:58:27.162660+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21300
  title: གསུང་འབུམ། པདྨ་ཉིན་བྱེད་དབང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C640:
      image_group_id: I1KG22063
      title: ''
      total_pages: 938
      order: 1
      base_file: C640.txt
    85AD:
      image_group_id: I1KG22064
      title: ''
      total_pages: 840
      order: 2
      base_file: 85AD.txt
    E52F:
      image_group_id: I1KG22065
      title: ''
      total_pages: 872
      order: 3
      base_file: E52F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
