id: I9A58C9BF
legacy_id: P009571
ocr_import_info:
  bdrc_scan_id: W1KG21300
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:35:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T10:40:31.584341+00:00'
last_modified: 2022-08-31 18:42:17.200782
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG21300
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG21300
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པདྨ་ཉིན་བྱེད་དབང་པོ།
  author: སི་ཏུ ༠༩་པདྨ་ཉིན་བྱེད་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6514032970085661
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG22063:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22063
      total_pages: 938
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22063.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6619573173198399
    legacy_id: v001
  I1KG22064:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22064
      total_pages: 840
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22064.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6402264754748873
    legacy_id: v002
  I1KG22065:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22065
      total_pages: 872
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG22065.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6513578897387227
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
