id: P009571
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG21300
  title: གསུང་འབུམ། པདྨ་ཉིན་བྱེད་དབང་པོ།
  author: ''
  volumes:
    57b75d1fed644c188a04424fa2caabad:
      image_group_id: I1KG22063
      title: ''
      volume_number: 1
      total_pages: 938
      base_file: v001.txt
    8c7e3d6b5df7418d8744e8a0ee58b344:
      image_group_id: I1KG22064
      title: ''
      volume_number: 2
      total_pages: 840
      base_file: v002.txt
    d63e125834fc408c966556360cbfcc23:
      image_group_id: I1KG22065
      title: ''
      volume_number: 3
      total_pages: 872
      base_file: v003.txt
